### PR TITLE
Guayadeque.po files for French Greek an Italian corrected and synchronized with the latest guayadeque.pot file

### PR DESCRIPTION
**Pull request by filochard**
Guayadeque.po files for French Greek an Italian corrected and synchronized with the latest guayadeque.pot file

### CODE REVIEW

**Comment by filochard** [comment]
The diff for those files may be huge but the next Pull Requests will have very short diff from now on...  :o)

They come from the dev branch of my repo after this one has been synchronized with your own dev branch

**Comment by thothix** [comment]
You are removing the custom translations at the end of the .po files. Those translations are not in the .pot file because they aren't in the source code, they come from external files like .conf.

I'm going to merge and put them back afterwards.

**Comment by thothix** [comment]
I need to find a way to handle this.

**Comment by filochard** [comment]
Sorry
I had deleted those lines because they were not in the pot file.... :-(

**Pull request merged**
