### PR TITLE
Add files via upload

### PR DESCRIPTION
**Pull request by filochard**
I uploaded in my fork (dev branch) and so replaced the previous Italian po file (aka /po/it/guayadeque.po) by a po file corrected and synchronized with the last guayadeque.pot

### CODE REVIEW

**Comment by filochard** [comment]
Italian po file corrected and synchronized with the last pot

**Comment by filochard** [comment]
I uploaded in my fork (dev branch) and so replaced the previous Greek po file (aka /po/el/guayadeque.po)  by a  po file corrected and synchronized with the last guayadeque.pot file
Same or the French po file  (aka /po/fr/guayadeque.po)

**Comment by filochard** [comment]
Sorry for the double request for each po file
Consider only the two last po files for fr an el

**Comment by filochard** [comment]
Hi Tiago
Sorry, I am not very familiar with the way to make pull requests  
the only good commits are those
https://github.com/thothix/guayadeque/pull/19/commits/e4f28fcd2f22de0b559cc8a7925d6df442428557
https://github.com/thothix/guayadeque/pull/19/commits/9c3a7709db374a2be3f926d409d9a83e2b67070c
https://github.com/thothix/guayadeque/pull/19/commits/67b4ff804d1e35013e2bbd16898cdce669bfe38c

all of them are synchronized wit the last pot file

**Comment by thothix** [comment]
Hi @filochard 

I saw your PR only now!
There's a lot of conflics and you based your changes in a very outdated file.
I was able to merge French and Greek files manually but Italian is very different. You'll need to do it again based in the current translation.

**Comment by thothix** [comment]
You can send me the Italian .po in the translation issue.
I'm going to close this PR.

**Comment by filochard** [comment]
> Hi @filochard
> 
> I saw your PR only now! There's a lot of conflics and you based your changes in a very outdated file. I was able to merge French and Greek files manually but Italian is very different. You'll need to do it again based in the current translation.

In my fork, I had  synchronized and corrected the very old .po files  for French, Greek and Italian with the .pot file existing then.
I thought it would be easier after this to bring future translations
As a consequence there was a very big diff then
That's certainly why there are conflicts now that the .pot file as been modified
I can synchronize again my .po files with the more recent .pot file from your code

About PR I thought that I could propose those .po files there, letting you merge them if you agree
(You are the only one to allow this)....

Post Scriptum
I have resolved the conflicts in my fork just now

Just tell me when your code is unchanged so that I can Request some pull with really synchronized corrected .po files

**Pull request closed without merging**
